export const SET_PLAYERS_NAMES = "SET_PLAYERS_NAMES";
export const CHANGE_CURRENT_PLAYER = "CHANGE_CURRENT_PLAYER";
export const HIDE_PLAYERS_FORM = "HIDE_PLAYERS_FORM";
export const SHOW_PLAYERS_FORM = "SHOW_PLAYERS_FORM";